import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Google Clone Next js 13",
  description: "Google clone Generated by create next app",
  icon: "favicon.svg",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"relative min-h-screen"}>
        {children}
        {/*footer*/}
        <Footer />
      </body>
    </html>
  );
}
